spring:
  application:
    name: smart-shop
  datasource:
    url: jdbc:h2:mem:smart-shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  servlet:
    context-path: /api/v1
